# Generated by Django 5.2.14 on 2026-06-06 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
